# Configuration for QR Code Generator
# Define the settings for QR code creation, output, appearance, and advanced options.

data:
  website: 'https://artistikath.de'    # Main URL to encode in the QR code
  instagram: 'https://instagram.com/artistikath'  # Optional Instagram URL
  tiktok: 'https://tiktok.com/@artistikath'       # Optional TikTok URL

output:
  qr_code_path: './files/output/custom_qr.png' # Path to save the generated QR code
  logo_path: './files/input/logo'  # Path without extension, will be dynamically determined
  final_path: './files/output_logo/qr_with_logo.png' # Path to save the final QR code with the logo
  output_format: 'PNG'          # Output format for the QR code image (e.g., PNG, JPEG)

appearance:
  fill_color: 'black'           # Foreground color of the QR code
  back_color: 'white'           # Background color of the QR code
  logo_size_ratio: 5            # Ratio to determine the size of the logo in the QR code
  padding: 10                   # Padding around the logo within the QR code
  border_color: null            # Optional border color distinct from the background
  foreground_pattern: 'squares' # Pattern for QR code modules (squares, dots)
  gradient:                     # Gradient settings (optional)
    enabled: false              # Enable or disable gradient
    start_color: 'black'        # Starting color for the gradient
    end_color: 'grey'           # Ending color for the gradient

qr_code:
  version: 1                    # QR Code version (1 to 40)
  error_correction: 'H'         # Error correction level (L, M, Q, H)
  box_size: 10                  # Size of each QR box (px)
  border: 4                     # Size of QR code border (boxes)
  width: 1200                    # Width of the QR code image (px)
  height: 1200                   # Height of the QR code image (px)
  quiet_zone: 4                 # Minimum quiet zone width (modules)
  background_image: null        # Path to an image to use as the background (optional)
  scale: 1.0                    # Scaling factor for the entire QR code

logo:
  shape: 'square'               # Shape of the logo area (circle, square)
